feat: forte item refund funtion
team-crescendo/larabot pull request #4
Opened 2020-12-16 05:35 UTC by 331leo

#2 아이템 청약철회 기능을 제작하였습니다.
`ㄹ ㅍ 청약철회 (Id,Mention)`
로 사용할수 있습니다.

![image](https://user-images.githubusercontent.com/30466064/102309334-e2aedc00-3fab-11eb-891e-16039bff38fc.png)

2020-12-16 05:40 UTC, HyungJu approved these changes

2020-12-16 14:20 UTC, GBS-Skile requested changes
코드 스타일 같은 경우에는 larabot 프로젝트에서 따로 합의된게 없기 때문에 굳이 지적 안했습니당

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +            return await ctx.send("아이템 삭제처리가 완료되지 않았습니다. 청약철회 처리를 취소합니다.")
다른 팀원분들 코드리뷰할때마다 항상 단골로 하는 코멘트인데 ㅋㅋ
중간에 오류가 나서 함수 실행을 종료(return)하는 코드는 `else:`로 빼지 마시고 `if`로 먼저 검사해주세요

indent가 가급적이면 늘어나지 않도록 코드를 짜는 게 좋습니다

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +            msg = await self.bot.wait_for('message',timeout=10.0, check=check)
10초 좀 빡빡하지 않을까요? 30초정도는 있는게 관리자 입장에서도 편할거같아요

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +            return m.author == ctx.author and m.channel == ctx.channel and m.content.isdigit and m.content in refundable_item_ids
```suggestion
            return m.author == ctx.author and m.channel == ctx.channel and m.content in refundable_item_ids
```

isdigit은 함수입니다. `m.content.isdigit()` 괄호붙여주는게 맞아요
근데 애초에 `m.content in refundable_item_ids`가 True가 되려면 논리적으로 isdigit()이 아닐리가 없기 때문에 아예 조건에서 제외하심이 어떨까 싶습니다

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +    @forte.command(aliases=['청약철회'],brief="포르테 아이템 구매를 청약철회 합니다.")
앞에 empty line 한 줄 있었으면좋겠어요...

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +            return await ctx.send("청약철회 가능한 아이템이 없습니다.")
이건 순서상 `send_text="어쩌구"` 하기 전으로 올려주시는게 좋을거같아요

2020-12-16 14:20 UTC, GBS-Skile commented on src/extensions/forte.py
> +        )
```suggestion
        await request("delete", f"/users/{user['id']}/items/{msg.content}")
```

리턴값 안쓸거면 괜히 헷갈리지 않게 해두시는게 좋을듯

2020-12-16 14:27 UTC, 331leo commented on src/extensions/forte.py
> +            return await ctx.send("아이템 삭제처리가 완료되지 않았습니다. 청약철회 처리를 취소합니다.")
잘 이해가 가지 않아서 질문드립니다!
```python
if result['expried'] == 0:
      return await ctx.send("아이템 삭제처리가 완료되지 않았습니다. 청약철회 처리를 취소합니다.")
```
이런식으로 수정하라는건가요?

2020-12-20 11:06 UTC, HyungJu commented
@331leo 수정 하신 내용은 Resolve 눌러주시고 리뷰 리리퀘 해주세용

2020-12-20 11:28 UTC, GBS-Skile approved these changes

2020-12-20 11:29 UTC, merged